language: node_js
node_js:
- '12.9'

cache:
  directories:
  - "node_modules"

install:
- npm install

script:
- npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  local-dir: build
  on:
    branch: master
